version: "3.9"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ENABLED: ${POSTGRES_ENABLED}

  redis:
    image: redis:7.0-alpine
    container_name: redis
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redisdata:/data

  prisma:
    container_name: prisma
    build:
      context: ./
      dockerfile: ./docker/prisma/Dockerfile
    ports:
      - 5555:5555 # NE PAS EXPOSE EN PROD
      - 5556:5556
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ENABLED: ${POSTGRES_ENABLED}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npm run start:prisma"
    # command: sh -c "tail -f /dev/null"

  socket:
    build: docker/node
    container_name: socket
    ports:
    - 4000:4000
    volumes:
      - ./socket:/home/node/app
    depends_on:
      - api
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
    command: sh -c "pnpm install && pnpm run start:dev"

  api:
    build: docker/node
    container_name: api
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
        - ./back:/home/node/app
    depends_on:
        - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ENABLED: ${POSTGRES_ENABLED}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      HOST: ${HOST}
    command: sh -c "pnpm prismix && npx prisma migrate dev && tail -f /dev/null"

volumes:
  modules:
  build:
  store:
  redisdata:
  pgdata:
