version: "3.9"

services:

  front:
    build:
      context: ./front
      target: frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: front
    ports:
      - 3000:3000
    volumes:
        - ./front:/home/node/app
        - modules:/home/node/app/node_modules
        - store:/home/node/app/.pnpm-store
    # depends_on:
    #     - api
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOSTNAME}
    command: sh -c "tail -f /dev/null" 

volumes:
  modules:
  build:
  store:
  redisdata:
  pgdata:
