version: "3.9"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ENABLED: ${POSTGRES_ENABLED}

  redis:
    image: redis:7.0-alpine
    container_name: redis
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redisdata:/data

  # CONTAINER UNIQUEMENT DEV, NE PAS DEPLOY SUR LA PROD
  prisma:
    container_name: prisma
    build:
      context: ./
      dockerfile: ./docker/prisma/Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ENABLED: ${POSTGRES_ENABLED}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npm run start:prisma"
    # command: sh -c "tail -f /dev/null"

  # socket:
  #   build: docker/node
  #   container_name: socket
  #   ports:
  #   - 4000:4000
  #   volumes:
  #     - ./socket:/home/node/app
  #   depends_on:
  #     - api
  #     - redis
  #   environment:
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     REDIS_PASS: ${REDIS_PASS}
  #     REDIS_URL: ${REDIS_URL}
  #     NODE_ENV: ${NODE_ENV}
  #     HOST: ${HOST}
  #   command: sh -c "pnpm install && pnpm run start:dev"

  api:
    build: docker/node
    container_name: api
    ports:
      - 3001:3001
    volumes:
        - ./back:/home/node/app
        - modules:/home/node/app/node_modules
        - build:/home/node/app/dist
        - store:/home/node/app/.pnpm-store
    depends_on:
        - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ENABLED: ${POSTGRES_ENABLED}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      HOST: ${HOSTNAME}
    # command: sh -c "pnpm prismix && npx prisma migrate dev && tail -f /dev/null"
    command: sh -c "npm i -g @nestjs/cli && pnpm db:migrate && tail -f /dev/null"

volumes:
  modules:
  build:
  store:
  redisdata:
  pgdata:
