FROM node:18.14-alpine

WORKDIR /home/node/app

#COPY ./back/src/models ./src/models
#COPY ./back/prisma ./prisma
#COPY ./docker/prisma/tsconfig.json .
#COPY ./docker/prisma/package.json .

#RUN touch src/main.ts && \
#	npm install

EXPOSE 5555
EXPOSE 5556
