import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.0.0',
  date: '2023-09-08T11:45:01.672Z',
};
export default meta;
