name: Frontend CI

on:
  push:
    branches:
      - '*'
      - '**'
      - '*/*'
      - '!master' 
      - '!**/backend'
      - '!backend/**'
      - '!**/backend/**'
    paths:
      - ".github/workflows/frontend-ci.yml"
      - "front/**"
      - "docker/node/**"
  pull_request:
    branches:
      - '*'
      - '**'
      - '*/*'
      - '!master' 
      - '!**/backend'
      - '!backend/**'
      - '!**/backend/**'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/frontend-ci.yml"
      - "front/**"
      - "docker/node/**"
  workflow_dispatch:

env:
  NODE_VERSION: 20

defaults:
  run:
    working-directory: front

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  lint-eslint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: front/pnpm-lock.yaml
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint

  lint-style:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: front/pnpm-lock.yaml
      - name: Install deps
        run: pnpm install
      - name: Lint style
        run: pnpm lint:style

  build-frontend:
    needs: [setup]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: front/pnpm-lock.yaml
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build

  build-and-push-in-registry:
    needs:
      - setup
      - lint-eslint
      - lint-style
      - build-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{env.GITHUB_TOKEN}}
      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          docker build \
          -t ${{ env.DOCKER_REGISTRY }}/front-image:latest \
          -f ./Dockerfile \
          --build-arg VITE_HOST=${{ env.VITE_HOST }} \
          --build-arg VITE_PORT=${{ env.VITE_PORT }} \
          --build-arg VITE_API42_UID=${{ env.VITE_API42_UID }} \
          --build-arg VITE_API42_SECRET=${{ env.VITE_API42_SECRET }} \
          --build-arg VITE_API_PORT=${{ env.VITE_API_PORT }} \
          --build-arg VITE_GAME_SOCKET_PORT=${{ env.VITE_GAME_SOCKET_PORT }} \
          --build-arg VITE_CHAT_SOCKET_PORT=${{ env.VITE_CHAT_SOCKET_PORT }} \
          --target production .

          echo "Pushing Docker image to GitHub Container Registry..."
          docker push ${{ env.DOCKER_REGISTRY }}/front-image:latest
    env:
      NODE_ENV: production
      GITHUB_TOKEN: ${{ secrets.CR_PAT }}
      DOCKER_REGISTRY: ghcr.io/theozerbibi
      VITE_HOST: ${{ vars.HOST }}
      VITE_API42_UID: ${{ secrets.API42_UID }}
      VITE_API42_SECRET: ${{ secrets.API42_SECRET }}
      VITE_PORT: 3000
      VITE_API_PORT: 3001
      VITE_GAME_SOCKET_PORT: 4000
      VITE_CHAT_SOCKET_PORT: 4001

