name: Game Socket CI

on:
  push:
    branches:
      - "*"
      - "**"
      - "*/*"
      - '!master' 
      - "!**/frontend"
      - "!frontend/**"
      - "!**/frontend/**"
    paths:
      - ".github/workflows/game-socket-ci.yml"
      - "sockets/game/**"
      - "docker/node/**"
  pull_request:
    branches:
      - "*"
      - "**"
      - "*/*"
      - '!master' 
      - "!**/frontend"
      - "!frontend/**"
      - "!**/frontend/**"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/game-socket-ci.yml"
      - "sockets/game/**"
      - "docker/node/**"
  workflow_dispatch:

env:
  NODE_VERSION: 20

defaults:
  run:
    working-directory: sockets/game

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  lint-eslint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: sockets/game/pnpm-lock.yaml
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint

  lint-prettier:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: sockets/game/pnpm-lock.yaml
      - name: Install deps
        run: pnpm install
      - name: Prettier
        run: pnpm prettier

  build-socket:
    needs: [setup]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: sockets/game/pnpm-lock.yaml
      - name: Install deps
        run: pnpm install
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Build
        run: pnpm build

  build-and-push-in-registry:
    needs:
      - setup
      - lint-eslint
      - lint-prettier
      - build-socket
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{env.GITHUB_TOKEN}}
      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_REGISTRY }}/game-socket-image:latest -f ../../docker/node/Dockerfile --target production .

          echo "Pushing Docker image to GitHub Container Registry..."
          docker push ${{ env.DOCKER_REGISTRY }}/game-socket-image:latest
    env:
      NODE_ENV: production
      GITHUB_TOKEN: ${{ secrets.CR_PAT }}
      DOCKER_REGISTRY: ghcr.io/theozerbibi
